apiVersion: apps/v1
kind: Deployment
metadata:
  name: seesee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seesee
  template:
    metadata:
      labels:
        app: seesee
    spec:
      containers:
      - image: okteto.dev/seesee:latest
        name: seesee
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2f9bdab8-2210-4249-9e24-1229eaa995b8"
        - name: Vless_Path
          value: "/vl5967"
        - name: Vmess_UUID
          value: "2f9bdab8-2210-4249-9e24-1229eaa995b8"
        - name: Vmess_Path
          value: "/vm56456"
        - name: Share_Path
          value: "/v2link"
